version: '3'
services:
  web:
    image: 172.31.44.24:8083/spring-boot-websocket-chat-demo:latest-v1
    ports:
      - "8040:8080"
    networks:
      - overlay
    environment:
      - SPRING_PROFILE=QA 
    deploy:
      replicas: 2

networks:
  overlay:
    external:
      name: epicnetwork
